# Generated by Django 3.0.7 on 2020-06-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200623_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='local',
            field=models.BooleanField(default=False),
        ),
    ]
