# Generated by Django 3.0.7 on 2020-06-23 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_schedulerow'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='users',
            field=models.ManyToManyField(through='app.ScheduleRow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medicines', to=settings.AUTH_USER_MODEL),
        ),
    ]
